ignoredBuiltDependencies:
  - sharp

overrides:
  '@babel/runtime@<7.26.10': '>=7.26.10'
  tar@=7.5.1: '>=7.5.2'
  tmp@<=0.2.3: '>=0.2.4'
  js-yaml@<3.14.2: '>=3.14.2'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  mdast-util-to-hast@>=13.0.0 <13.2.1: '>=13.2.1'
