export const MOCK_Participants = [
  {
    id: 1,
    name: "Taha Dostifam",
    title: "Co Founder",
    picture: "/Participants/tahadostifam.jpeg",
    github: "https://github.com/tahadostifam",
    mastodon: "https://mastodon.social/@tahadostifam",
    daramet: "https://daramet.com/tahadostifam",
    telegram: "https://t.me/tahadostifam",
  },
  {
    id: 2,
    name: "Mohammad Kolagar",
    title: "Software Architecture",
    picture: "/Participants/ctirouzh.png",
    github: "https://github.com/ctirouzh",
    mastodon: "",
    daramet: "",
    telegram: "https://t.me/ctirouzh",
  },
  {
    id: 3,
    name: "Amir Rafati",
    title: "Back-End Developer",
    picture: "/Participants/AssassinRobot.jpeg",
    github: "https://github.com/AssassinRobot.jpeg",
    mastodon: "https://mastodon.social/@tahadostifam",
    daramet: "https://daramet.com/tahadostifam",
    telegram: "https://t.me/tahadostifam",
  },
  {
    id: 4,
    name: "Reza TG",
    title: "Back-End Developer",
    picture: "/Participants/rezatg.jpeg",
    github: "https://github.com/rezatg",
    mastodon: "",
    daramet: "",
    telegram: "https://t.me/dll_as",
  },
];