import { Contributor, ContributorCategory } from "./type";

export const categories: ContributorCategory[] = [
  "Core Team",
  "Website Team",
];

export const contributorsArray: Contributor[] = [
  {
    id: 1,
    name: "Taha Dostifam",
    nameFa: "طاها دوستی‌فام",
    category: "Core Team",
    tags: ["Creator"],
    picture: "https://avatars.githubusercontent.com/tahadostifam",
    github: "https://github.com/tahadostifam",
    mastodon: "https://mastodon.social/@tahadostifam",
    daramet: "https://daramet.com/tahadostifam",
    telegram: "https://t.me/tahadostifam",
  },
  {
    id: 2,
    name: "Tyler",
    nameFa: "تایلر",
    picture: "https://avatars.githubusercontent.com/TheJudge26",
    github: "https://github.com/TheJudge26",
    category: "Core Team",
    tags: ["Compiler", "Standard library"]
  },
  {
    id: 3,
    name: "Alisan",
    nameFa: "علیسان",
    category: "Website Team",
    tags: ["Website Frontend"],
    picture: "https://avatars.githubusercontent.com/azcpcf",
    github: "https://github.com/azcpcf",
    daramet: "https://daramet.com/oogway",
    telegram: "https://t.me/azcpcf",
  },
  {
    id: 4,
    name: "Saeed Dayani",
    nameFa: "سعید دیانی",
    category: "Website Team",
    tags: ["Website Frontend"],
    picture: "https://avatars.githubusercontent.com/talionsd",
    github: "https://github.com/talionsd",
    telegram: "https://t.me/talionsd",
  },
  {
    id: 5,
    name: "MrPi",
    nameFa: "مستر پی",
    category: "Website Team",
    tags: ["Website Frontend"],
    picture: "https://avatars.githubusercontent.com/imMrPi",
    github: "https://github.com/imMrPi",
    telegram: "https://t.me/imMrPi",
  },
  {
    id: 6,
    name: "meshya",
    nameFa: "مشیا",
    category: "Website Team",
    tags: ["Website Frontend"],
    picture: "https://avatars.githubusercontent.com/meshya",
    github: "https://github.com/meshya",
    mastodon: "https://mas.to/@meshya",
    daramet: "https://daramet.com/meshya",
    telegram: "https://t.me/meshyah",
  },
  {
    id: 7,
    name: "Mahdi Rahmani",
    nameFa: "مهدی رحمانی",
    category: "Website Team",
    tags: ["Website Frontend"],
    picture: "https://avatars.githubusercontent.com/u/110809899?v=4",
    github: "https://github.com/MahdiRahmany",
    linkedin: "https://www.linkedin.com/in/mahdirahmany",
    email: "mahdirahmani.cm@gmail.com",
    telegram: "https://t.me/Mahdy_l",
  },
  {
    id: 8,
    name: "dallas",
    nameFa: "دالاس",
    category: "Core Team",
    tags: ["Compiler"],
    picture: "https://avatars.githubusercontent.com/dll-as",
    github: "https://github.com/dll-as",
    telegram: "https://t.me/dll_as",
  },
  {
    id: 9,
    name: "CluvexStudio",
    nameFa: "کلاوکس استودیو",
    category: "Core Team",
    tags: ["Compiler", "Standard library"],
    picture: "https://avatars.githubusercontent.com/CluvexStudio",
    github: "https://github.com/CluvexStudio",
    telegram: "https://t.me/CluvexStudio",
  }
];
